global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
      # Forward X-Traefik-* headers to backends

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: DEBUG

tracing:
  otlp:
    grpc:
      endpoint: otel-collector:4317
      insecure: true

